mmt-finance/clmm-sdk

src/modules/poolModule.ts
src/types.ts
src/utils/poolUtils.ts
tests/get-all-pool.test.ts
tests/init-sdk.spec.ts

* Fixed hardcoded url issue in pool module
* Added AprBreakdown in GetAllPools interface

Feature: Add apr breakdown

---

package.json

* Boost version to 1.0.2
* Add script `yarn release`

chore: boost version and add yarn release

---

package.json
src/modules/poolModule.ts
src/types.ts
tests/decimal-utils.ts
tests/get-all-pool.test.ts

feat: add apr breakdown

---

package.json
src/modules/poolModule.ts
tests/get-all-pool.test.ts
yarn.lock

* Add validation = true/false at get Pool & get all pools.

feat: add option for validation when getting pools

---

package.json
src/index.ts
src/types.ts
tests/best-route.test.ts

1. export types
2. update best route test code

feat: export types

---

src/modules/poolModule.ts
tests/apr.test.ts

change apr estimation back to +-0.1%

chore: change apr estimation back to +-0.1%

---

package.json

chore: boost version to 1.0.11

---

package.json
src/modules/poolModule.ts
src/sdk.ts
src/utils/poolUtils.ts
tests/init-sdk.spec.ts

1. sdk init add header & test code

feat: sdk init add header & test code

---

src/modules/positionModule.ts

Add null check in getUserPositionsUsdValue

fix: fix the null position from getUserPositionsUsdValue

---

package.json
src/modules/routeModule.ts
src/utils/constants.ts
src/utils/poolUtils.ts
tests/best-route.test.ts
tests/fetch-tick-liquiditity.test.ts

1. fix router big amount & add test code
2. fix fetchAllTickLiquidities bug

feat: fix router big amount

---

package.json
src/utils/math/tickMath.ts
tests/apr.test.ts
tests/tick-math.test.ts

1. fix sqrtPriceX64ToTickIndexWithTickSpacing 
2.  test code

feat: fix sqrtPriceX64ToTickIndexWithTickSpacing & test code

---

package.json
src/modules/routeModule.ts
tests/best-route.test.ts

1. fetch router add output
2. test

feat: fetch router add output

---

src/modules/routeModule.ts
tests/best-route.test.ts

1. dry run swap in one transaction
2. test code

feat: dry run swap in one transaction

---

package.json
src/modules/routeModule.ts

feat: rollback best route code

---

package.json
src/modules/poolModule.ts

feat: apy bug

---

package.json
src/modules/poolModule.ts
src/utils/math/tickMath.ts
tests/get-pool.test.ts

feat: fix sqrt price check bug

---

package.json
tests/get-all-pool.test.ts
tests/get-user-positions-usd-value.test.ts

feat: update version

---

package.json
src/modules/poolModule.ts

feat: batch get pools object

---

src/modules/poolModule.ts
src/utils/poolUtils.ts
tests/apr.test.ts
tests/get-all-pool.test.ts

1. get apr from api service
2. test on dev

feat: get apr from api service

---

package.json
src/modules/positionModule.ts
src/utils/math/commonMath.ts

feat: fix negative apr

---

package.json
src/config.ts

feat: upgrade contract

---

src/modules/positionModule.ts
src/utils/math/commonMath.ts
tests/get-user-positions-usd-value.test.ts

fix: tickIndex calculate error

---

package.json

chore: change version

---

package.json
src/modules/poolModule.ts

feat: optimize apr

---

src/utils/math/tickMath.ts
tests/convert-test.test.ts

1.  i128 convert func
2. test code

feat: i128 convert func

---

package.json
src/modules/poolModule.ts
tests/get-min-tick-range-factor.test.ts

1. batch get min_range_factor
2. test code

feat: change batch get min_range_factor

---

package.json
src/modules/positionModule.ts
tests/get-all-user- position.test.ts

1. get user position func add tokens & pools param
2. test code

feat: get user position func add tokens & pools param

---

package.json
src/types.ts

feat: all pool add isDeprecated field

---

package.json
src/config.ts

feat: update package id

---

package.json
src/modules/poolModule.ts
tests/apr.test.ts

feat: update round up
